# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_add_word.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_Add_Word(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(975, 754)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(40, 160, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(130, 270, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.palavra = QtWidgets.QLineEdit(Form)
        self.palavra.setGeometry(QtCore.QRect(230, 150, 541, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.palavra.setFont(font)
        self.palavra.setStyleSheet("background-color: lightblue; /* Azul claro */\n"
"")
        self.palavra.setText("")
        self.palavra.setObjectName("palavra")
        self.traducao = QtWidgets.QLineEdit(Form)
        self.traducao.setGeometry(QtCore.QRect(230, 250, 541, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.traducao.setFont(font)
        self.traducao.setStyleSheet("background-color: lightblue; /* Azul claro */\n"
"")
        self.traducao.setText("")
        self.traducao.setObjectName("traducao")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 700, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color:White;\n"
"    color: black;\n"
"    border-radius: 10px;\n"
"    border: 2px solid black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: Gray;\n"
"    color: white;\n"
"    border: 2px solid white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:Gray;\n"
"    border: 2px solid yellow;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Transletion"))
        self.label.setText(_translate("Form", "World"))
        self.pushButton_2.setText(_translate("Form", "return"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Tela_Add_Word()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
