# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class tela_edit(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(974, 752)
        self.lista = QtWidgets.QListWidget(Form)
        self.lista.setGeometry(QtCore.QRect(40, 30, 531, 411))
        self.lista.setObjectName("lista")
        self.informacoes = QtWidgets.QLabel(Form)
        self.informacoes.setGeometry(QtCore.QRect(40, 460, 531, 61))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.informacoes.setFont(font)
        self.informacoes.setStyleSheet("background-color: lightblue; /* Azul claro */\n"
"")
        self.informacoes.setObjectName("informacoes")
        self.edicoes = QtWidgets.QLineEdit(Form)
        self.edicoes.setGeometry(QtCore.QRect(40, 550, 531, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.edicoes.setFont(font)
        self.edicoes.setStyleSheet("background-color: lightblue; /* Azul claro */\n"
"")
        self.edicoes.setText("")
        self.edicoes.setObjectName("edicoes")
        self.confirm = QtWidgets.QPushButton(Form)
        self.confirm.setGeometry(QtCore.QRect(0, 700, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.confirm.setFont(font)
        self.confirm.setStyleSheet("QPushButton {\n"
"    background-color:White;\n"
"    color: black;\n"
"    border-radius: 10px;\n"
"    border: 2px solid black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: Gray;\n"
"    color: white;\n"
"    border: 2px solid white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:Gray;\n"
"    border: 2px solid yellow;\n"
"}")
        self.confirm.setObjectName("confirm")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.informacoes.setText(_translate("Form", "TextLabel"))
        self.confirm.setText(_translate("Form", "Return"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = tela_edit()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
    
    

