# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lets_try.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_lets_Try(object):
    def setupUi(self, lets_Try):
        lets_Try.setObjectName("lets_Try")
        lets_Try.resize(968, 749)
        self.label = QtWidgets.QLabel(lets_Try)
        self.label.setGeometry(QtCore.QRect(0, 0, 971, 751))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("download (1).jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(lets_Try)
        self.frame.setGeometry(QtCore.QRect(720, 190, 111, 101))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.reset = QtWidgets.QPushButton(lets_Try)
        self.reset.setGeometry(QtCore.QRect(190, 90, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.reset.setFont(font)
        self.reset.setObjectName("reset")
        self.label_Chet = QtWidgets.QLabel(lets_Try)
        self.label_Chet.setGeometry(QtCore.QRect(320, 350, 251, 41))
        self.label_Chet.setObjectName("label_Chet")
        self.pergunta = QtWidgets.QLabel(lets_Try)
        self.pergunta.setGeometry(QtCore.QRect(190, 160, 481, 61))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pergunta.setFont(font)
        self.pergunta.setStyleSheet("background-color: lightblue; /* Azul claro */\n"
"")
        self.pergunta.setObjectName("pergunta")
        self.chet = QtWidgets.QPushButton(lets_Try)
        self.chet.setGeometry(QtCore.QRect(190, 340, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.chet.setFont(font)
        self.chet.setObjectName("chet")
        self.resposta = QtWidgets.QLineEdit(lets_Try)
        self.resposta.setGeometry(QtCore.QRect(190, 250, 481, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.resposta.setFont(font)
        self.resposta.setStyleSheet("background-color: lightblue; /* Azul claro */\n"
"")
        self.resposta.setText("")
        self.resposta.setObjectName("resposta")
        self.edit = QtWidgets.QPushButton(lets_Try)
        self.edit.setGeometry(QtCore.QRect(360, 90, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.edit.setFont(font)
        self.edit.setObjectName("edit")
        self.i_know = QtWidgets.QPushButton(lets_Try)
        self.i_know.setGeometry(QtCore.QRect(540, 90, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.i_know.setFont(font)
        self.i_know.setObjectName("i_know")
        self.pushButton_2 = QtWidgets.QPushButton(lets_Try)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 690, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color:White;\n"
"    color: black;\n"
"    border-radius: 10px;\n"
"    border: 2px solid black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: Gray;\n"
"    color: white;\n"
"    border: 2px solid white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:Gray;\n"
"    border: 2px solid yellow;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(lets_Try)
        QtCore.QMetaObject.connectSlotsByName(lets_Try)

    def retranslateUi(self, lets_Try):
        _translate = QtCore.QCoreApplication.translate
        lets_Try.setWindowTitle(_translate("lets_Try", "Form"))
        self.reset.setText(_translate("lets_Try", "Reset"))
        self.label_Chet.setText(_translate("lets_Try", "TextLabel"))
        self.pergunta.setText(_translate("lets_Try", "TextLabel"))
        self.chet.setText(_translate("lets_Try", "chet"))
        self.edit.setText(_translate("lets_Try", "Edit"))
        self.i_know.setText(_translate("lets_Try", "I know"))
        self.pushButton_2.setText(_translate("lets_Try", "return"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    lets_Try = QtWidgets.QWidget()
    ui = Ui_lets_Try()
    ui.setupUi(lets_Try)
    lets_Try.show()
    sys.exit(app.exec_())
